# see https://docs.docker.com/compose/compose-file/

services:
  builder:
    command: >
      /usr/bin/tail -f /dev/null
    container_name: signalk-builder
    image: node:20
    stop_grace_period: 2s
    volumes:
      - .:/opt
networks:
  default:
    driver: bridge
