#ifndef HAJO_FRIDGE_CONFIG_H
#define HAJO_FRIDGE_CONFIG_H

#define FAN_1_OUT_POWER GPIO_NUM_3
#define FAN_1_OUT_PWM   GPIO_NUM_5
#define FAN_1_IN_SENSE  GPIO_NUM_7
#define FAN_2_OUT_POWER GPIO_NUM_6
#define FAN_2_OUT_PWM   GPIO_NUM_8
#define FAN_2_IN_SENSE  GPIO_NUM_10
#define FAN_3_OUT_POWER GPIO_NUM_9
#define FAN_3_OUT_PWM   GPIO_NUM_11
#define FAN_3_IN_SENSE  GPIO_NUM_12

#define TEMP_1_IN  GPIO_NUM_39
#define TEMP_2_IN  GPIO_NUM_37
#define TEMP_3_IN  GPIO_NUM_35
#define TEMP_4_IN  GPIO_NUM_33

#endif //HAJO_FRIDGE_CONFIG_H
