idf_component_register(
        SRCS
        "lib/gpio_define.c"
        "lib/gpio_task.c"
        "lib/nvs_main.c"
        "lib/rest_main.c"
        "lib/rest_server.c"
        "gpio_logic.c"
        "ontozo_main.c"
        "rest_handler.c"
        "test_util.c"
        INCLUDE_DIRS
        "."
        "lib"
)
