#ifndef ONTOZO_CONFIG_H
#define ONTOZO_CONFIG_H

#include "driver/gpio.h"

#define GPIO_INPUT_LEVEL_0  GPIO_NUM_26
#define GPIO_INPUT_LEVEL_1  GPIO_NUM_25
#define GPIO_INPUT_LEVEL_2  GPIO_NUM_33
#define GPIO_INPUT_LEVEL_3  GPIO_NUM_32

#define GPIO_INPUT_BUTTON_START     GPIO_NUM_12
#define GPIO_INPUT_BUTTON_STOP      GPIO_NUM_14

#endif //ONTOZO_CONFIG_H
