#ifndef HAJO_ENGINE_SENDER_INTERNAL_H
#define HAJO_ENGINE_SENDER_INTERNAL_H

#define PIN_OUTPUT_MAIN      GPIO_NUM_3
#define PIN_OUTPUT_START     GPIO_NUM_5
#define PIN_OUTPUT_STOP      GPIO_NUM_7
#define PIN_OUTPUT_LIGHT     GPIO_NUM_9
#define PIN_OUTPUT_BUZZER    GPIO_NUM_11

#endif //HAJO_ENGINE_SENDER_INTERNAL_H
