#ifndef HAJO_CONFIG_H
#define HAJO_CONFIG_H

#define N2K_GPIO_NUM_RX         GPIO_NUM_16
#define N2K_GPIO_NUM_STANDBY    GPIO_NUM_10
#define N2K_GPIO_NUM_TX         GPIO_NUM_17

#define GPIO_NUM_DEVICE_TYPE_0  GPIO_NUM_1
#define GPIO_NUM_DEVICE_TYPE_1  GPIO_NUM_2
#define GPIO_NUM_DEVICE_TYPE_2  GPIO_NUM_4

#define GPIO_NUM_SDCARD_MISO  GPIO_NUM_37
#define GPIO_NUM_SDCARD_CLK   GPIO_NUM_36
#define GPIO_NUM_SDCARD_MOSI  GPIO_NUM_35
#define GPIO_NUM_SDCARD_CS    GPIO_NUM_34

#define GPIO_NUM_LOGGER_BUTTON_1    GPIO_NUM_36 // L_DC
#define GPIO_NUM_LOGGER_BUTTON_2    GPIO_NUM_34 // L_RESET
#define GPIO_NUM_LOGGER_LED_GREEN   GPIO_NUM_21 // L_CS
#define GPIO_NUM_LOGGER_LED_RED     GPIO_NUM_38 // T_IRQ

#define GPIO_NUM_LED_POWER          GPIO_NUM_15

// defined by GPIO_NUM_DEVICE_TYPE_* pins
#define DEVICE_TYPE_UNKNOWN_0 0b000
#define DEVICE_TYPE_LOGGER 0b001
#define DEVICE_TYPE_UNKNOWN_2 0b010
#define DEVICE_TYPE_UNKNOWN_3 0b011
#define DEVICE_TYPE_UNKNOWN_4 0b100
#define DEVICE_TYPE_GAUGE_DISPLAY 0b101
#define DEVICE_TYPE_BATTERY_MONITOR 0b110
#define DEVICE_TYPE_UNKNOWN_7 0b111
#define DEVICE_TYPE_ALL 0b1111111

#define GPIO_ATTITUDE_GND   GPIO_NUM_11
#define GPIO_ATTITUDE_3V3   GPIO_NUM_12
#define GPIO_ATTITUDE_I2C_SDA   GPIO_NUM_9
#define GPIO_ATTITUDE_I2C_SDC   GPIO_NUM_8

#ifdef CONFIG_DEVICE_TYPE_LOGGER
#define DEVICE_TYPE DEVICE_TYPE_LOGGER
#elif CONFIG_DEVICE_TYPE_GAUGE_DISPLAY
#define DEVICE_TYPE DEVICE_TYPE_GAUGE_DISPLAY
#elif CONFIG_DEVICE_TYPE_BATTERY_MONITOR
#define DEVICE_TYPE DEVICE_TYPE_BATTERY_MONITOR
#else
#define DEVICE_TYPE DEVICE_TYPE_ALL
#endif

#endif //HAJO_CONFIG_H
