#ifndef HAJO_CONFIG_H
#define HAJO_CONFIG_H

#define N2K_GPIO_NUM_RX         GPIO_NUM_16
#define N2K_GPIO_NUM_TX         GPIO_NUM_17

#define GPIO_ATTITUDE_GND       GPIO_NUM_11
#define GPIO_ATTITUDE_3V3       GPIO_NUM_12
#define GPIO_ATTITUDE_I2C_SDA   GPIO_NUM_9
#define GPIO_ATTITUDE_I2C_SDC   GPIO_NUM_8

#define GPIO_NUM_GATEWAY_ACTISENSE_TX     GPIO_NUM_38
#define GPIO_NUM_GATEWAY_ACTISENSE_RX     GPIO_NUM_37
#define GPIO_NUM_GATEWAY_WITMOTION_TX     GPIO_NUM_5
#define GPIO_NUM_GATEWAY_WITMOTION_RX     GPIO_NUM_3

#define GPIO_NUM_LED_POWER      GPIO_NUM_15

#define GPIO_NUM_DEVICE_TYPE_0  GPIO_NUM_1
#define GPIO_NUM_DEVICE_TYPE_1  GPIO_NUM_2
#define GPIO_NUM_DEVICE_TYPE_2  GPIO_NUM_4

// defined by GPIO_NUM_DEVICE_TYPE_* pins, pin order: 012
#define DEVICE_TYPE_UNKNOWN_0 0b000
#define DEVICE_TYPE_FRIDGE      0b0001
#define DEVICE_TYPE_RUDDER      0b0010
#define DEVICE_TYPE_ENGINE_SENDER   0b0011
#define DEVICE_TYPE_GATEWAY     0b0100
#define DEVICE_TYPE_DISPLAY     0b0101
#define DEVICE_TYPE_BATTERY     0b0110
#define DEVICE_TYPE_ENGINE_DISPLAY   0b0111
#define DEVICE_TYPE_ALL         0b1000  // this is just to enable compilation of the whole project in CLion

#if CONFIG_DEVICE_TYPE_BATTERY
#define DEVICE_TYPE DEVICE_TYPE_BATTERY
#elif CONFIG_DEVICE_TYPE_DISPLAY
#define DEVICE_TYPE DEVICE_TYPE_DISPLAY
#elif CONFIG_DEVICE_TYPE_ENGINE_DISPLAY
#define DEVICE_TYPE DEVICE_TYPE_ENGINE_DISPLAY
#define CHECK_DEVICE_TYPE   0
#elif CONFIG_DEVICE_TYPE_ENGINE_SENDER
#define DEVICE_TYPE DEVICE_TYPE_ENGINE_SENDER
#define CHECK_DEVICE_TYPE   0
#elif CONFIG_DEVICE_TYPE_FRIDGE
#define DEVICE_TYPE DEVICE_TYPE_FRIDGE
#elif CONFIG_DEVICE_TYPE_GATEWAY
#define DEVICE_TYPE DEVICE_TYPE_GATEWAY
#elif CONFIG_DEVICE_TYPE_RUDDER
#define DEVICE_TYPE DEVICE_TYPE_RUDDER
#else
#define DEVICE_TYPE DEVICE_TYPE_ALL
#endif

#ifndef CHECK_DEVICE_TYPE
#define CHECK_DEVICE_TYPE   1
#endif

#endif //HAJO_CONFIG_H
